FROM openjdk:17

RUN mkdir /app

COPY src /app

WORKDIR /app/home
CMD dir
CMD java --module-path ..\openjfx-18.0.2_windows-x64_bin-sdk\javafx-sdk-18.0.2\lib --add-modules javafx.controls,javafx.fxml Main.java